### ISSUE TITLE
使用出现Aliyun::OSS::ServerError

### ISSUE THREAD

**Issue by huzhijia** [huacnlee/activestorage-aliyun#7]
storate.yml

```yml
local:
  service: Aliyun
  access_key_id: "*******"
  access_key_secret: "******"
  bucket: "product"
  endpoint: "http://oss-cn-beijing.aliyuncs.com"
  # path prefix, default: /
  path: "/product"
  # Bucket mode: [public, private], default: public
  mode: "private"
```

model

```rb
class Product < ApplicationRecord

	belongs_to :category

	has_many :order_items

	has_one_attached :product_image #产品首图

	enum status:{
		'未发布': false,
		'已发布': true
	}
end
```

views

```erb
<%=f.file_field :product_image %>
```

controller.rb
```rb
  create方法代码
  @product = Product.new(product_params)
  @product.save

private
  def product_params
      params.require(:product).permit!
    end
```
出现一下oss服务问题：
```
Aliyun::OSS::ServerError (The specified object is not valid. RequestId: 5AF11498A645AE2A87914BD3):

app/controllers/admin/products_controller.rb:12:in `create'
```
